# Generated by Django 5.2.8 on 2025-11-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('is_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waha_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_api.wahainstance')),
            ],
            options={
                'unique_together': {('chat_id', 'waha_instance')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('direction', models.CharField(choices=[('in', 'Recebida'), ('out', 'Enviada')], max_length=10)),
                ('sender', models.CharField(max_length=255)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat')),
                ('waha_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_api.wahainstance')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('message_id', 'waha_instance')},
            },
        ),
    ]
