# Generated by Django 5.2.8 on 2025-11-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('whatsapp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccess',
            name='waha_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_api.wahainstance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_instances',
            field=models.ManyToManyField(blank=True, to='whatsapp_api.wahainstance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
